name: on_tag
permissions:
    contents: write
    pull-requests: write
on:
    push:
        tags:
            - '*'
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - name: Build
              run: |
                  bun i
                  bun run build

                  cd dist/chromium
                  zip -r ../../chromium.zip *

                  cd ../firefox
                  zip -r ../../firefox.zip *
                  cd ../../
            - name: Release
              run: |
                  git config --global user.email "148579276+otis11@users.noreply.github.com"
                  git config --global user.name "on_tag_yml_release"

                  gh release create "$GITHUB_REF_NAME" --title "$GITHUB_REF_NAME" ./chromium.zip ./firefox.zip
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
